//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparischiWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public int id { get; set; }
        public string address_name { get; set; }
        public string address_content { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> selected_address { get; set; }
    
        public virtual User User { get; set; }
    }
}
